name: Waka Readme

on:
  push:
    branches:
      - master
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-all-time:
    name: Update all-time WakaTime stats
    runs-on: ubuntu-latest

    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SECTION_NAME: waka_all_time
          TIME_RANGE: all_time
          LANG_COUNT: 10
          SHOW_TIME: true
          SHOW_TOTAL: true
          SHOW_TITLE: false
          CODE_LANG: text
          BLOCKS: █░
          STOP_AT_OTHER: true
          IGNORED_LANGUAGES: YAML JSON TOML
          COMMIT_MESSAGE: Update all-time WakaTime stats
          TARGET_BRANCH: master
          TARGET_PATH: README.md
          COMMITTER_NAME: GitHubActionBot
          COMMITTER_EMAIL: action-bot@github.com

  update-week:
    name: Update recent 7-day WakaTime stats
    runs-on: ubuntu-latest
    needs: update-all-time

    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SECTION_NAME: waka_week
          TIME_RANGE: last_7_days
          LANG_COUNT: 10
          SHOW_TIME: true
          SHOW_TOTAL: true
          SHOW_TITLE: false
          CODE_LANG: text
          BLOCKS: █░
          STOP_AT_OTHER: true
          IGNORED_LANGUAGES: YAML JSON TOML
          COMMIT_MESSAGE: Update weekly WakaTime stats
          TARGET_BRANCH: master
          TARGET_PATH: README.md
          COMMITTER_NAME: GitHubActionBot
          COMMITTER_EMAIL: action-bot@github.com
