name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-readme:
    name: Update WakaTime Stats
    runs-on: ubuntu-latest

    steps:
      - name: Update all-time WakaTime stats
        uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SECTION_NAME: waka_all_time
          TIME_RANGE: all_time
          LANG_COUNT: 8
          SHOW_TIME: true
          SHOW_TOTAL: true
          CODE_LANG: text
          BLOCKS: █░

      - name: Update weekly WakaTime stats
        uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SECTION_NAME: waka_week
          TIME_RANGE: last_7_days
          LANG_COUNT: 8
          SHOW_TIME: true
          SHOW_TOTAL: true
          CODE_LANG: text
          BLOCKS: █░
